FROM eclipse-temurin:21-jdk AS build

ARG MODULE
WORKDIR /workspace

COPY . .
RUN sed -i 's/\r$//' ./mvnw && chmod +x ./mvnw && ./mvnw -pl ${MODULE} -am package -DskipTests

FROM eclipse-temurin:21-jre

ARG MODULE
WORKDIR /app
COPY --from=build /workspace/${MODULE}/target/*.jar app.jar

EXPOSE 8040 8761 8889 9090
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
